[Variables]
;date_1
January=1月
February=2月
March=3月
April=4月
May=5月
June=6月
July=7月
August=8月
September=9月
October=10月
November=11月
December=12月
;date_2
Monday=星期一
Tuesday=星期二
Wednesday=星期三
Thursday=星期四
Friday=星期五
Saturday=星期六
Sunday=星期天
;time
Your User Name=
;weather
Today's=Today's
Feels like=Feels like
Night temp=夜间温度
Day temp=日间温度
;battery_1
in=电池电源
out=外接电源
;battery_2
null=没有电池
in=充电中
low=低电量
middle=中等电量
high=高电量
